server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/health-app-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
cors:
  allowed:
    origins: http://localhost:5173

security:
  jwt:
    secret-key: 5cea9ea4a0149217c7bf7c90ee7d61dc4713711cdcd812fc96ec81234b05d838
    expiration-time: 1075200000

health-prediction-service:
  url: http://localhost:5000

gemini:
  api:
    key: AIzaSyC-CYLjKCbDLveeacE5ohpqUH5WOiHapr4
    version: v1beta
  model: gemini-2.0-flash
  system-instruction: 'You are a health and wellness advisor analyzing health questionnaire responses. IMPORTANT GUIDELINES: Provide evidence based health suggestions only, Focus on lifestyle improvements, not medical diagnoses, Always recommend consulting healthcare professionals for serious concerns, Be specific and actionable in your suggestions, Consider the whole person approach (physical, mental, lifestyle), Never provide specific medication recommendations, If symptoms suggest serious conditions, strongly recommend medical consultation. Your role is to provide general wellness guidance, not medical diagnosis or treatment.'
  max-output-tokens: 2048
  temperature: 0.3
  top-p: 0.90
  timeout-ms: 30000

logging:
  level:
    root: INFO
